### ISSUE TITLE
Error when chaining open call after networkOn

### ISSUE THREAD

**Issue by PyvesB** [paulmelnikow/icedfrisby-nock#3]
Hello there!

I've been working on adding some tests to the CodeClimate service in shields (see pull request [1613](https://github.com/badges/shields/pull/1613)). I need to mock one request and allow other HTTP connections and therefore followed the example in the Readme.

Nevertheless the following error is thrown:
`TypeError: t.create(...).get(...).intercept(...).networkOn(...).open is not a function`

In the end I've come up with a solution that seems to work, but I'm reporting this issue anyway. 😉 

Cheers,

Pyves

**Comment by paulmelnikow** [comment]
I’m happy to look at this! Is the readme example a complete recipe to reproduce the problem?

**Comment by PyvesB** [comment]
I believe so, unless I'm missing something. I was trying to write the following test in shields:
`t.create('malformed response for inner specific repo query')
  .get('/maintainability/angular/angular.js.json')
  .intercept(nock => nock('https://api.codeclimate.com')
    .get('/v1/repos/526933117e00a40567008444/snapshots/5ab4427859c16c0001003cad')
    .reply(200, {})) // No data.
  .networkOn() // Combined with allowUnmocked: true, this allows the outer user repos query to go through.
  .open()
  .expectJSON({
    name: 'maintainability',
    value: 'invalid'
  });`

**Comment by paulmelnikow** [comment]
Huh, I think the `.open()` call should not be there. There is no `open` method in IcedFrisby, nor in this module.

**Comment by paulmelnikow** [comment]
Thanks! Sorry I missed this!
